baseURL = 'https://davidbekaert.photography/'
languageCode = 'en-us'
title = 'David Bekaert Photography'
theme = "PhotoPF"

[menu]
[[menu.main]]
  pageRef="/"
  name = 'Home'
  URL = "/"
  weight = 10
[[menu.main]]
  pageRef="/mythologies/"
  name = 'Mythologies'
    URL = "/mythologies/"
  weight = 20
[[menu.main]]
  pageRef="/mfwc/"
  name = "Making Friends with Crows"
    URL = "/mfwc/"
  weight = 30
[[menu.main]]
  pageRef="/territory/"
<<<<<<< HEAD
  name = 'Territory of The Unconcious'
  url = '/territory/'
=======
  name = 'Territory of the Unconcious'
    URL = "/territory/"
>>>>>>> b48f488fc0a09fee66acf74fcf80352ff61f3d07
  weight = 40
[[menu.main]]
  pageRef=""  
  name = ''
  weight = 99
[[menu.main]]
  pageRef="/info/"  
  name = 'Info'
    URL = "/info/"
  weight = 100
