baseURL = 'https://davidbekaert.photography/'
languageCode = 'en-us'
title = 'David Bekaert Photography'
theme = "PhotoPF"

[menu]
[[menu.main]]
  pageRef="/"
  name = 'Home'
  weight = 10
[[menu.main]]
  pageRef="/mythologies/"
  name = 'Mythologies'
  weight = 20
[[menu.main]]
  pageRef="/mfwc/"
  name = "Making Friends with Crows"
  weight = 30
[[menu.main]]
  pageRef="/territory/"
  name = 'Territory of the Unconcious'
  weight = 40
[[menu.main]]
  pageRef=""  
  name = ''
  weight = 99
[[menu.main]]
  pageRef="/info/"  
  name = 'Info'
  weight = 100
